routes/web.php
<?php

use App\Mail\WelcomeMail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Sử dụng phương thức GET cho route hiển thị form contact
Route::get('/contact', 'App\Http\Controllers\ContactController@showForm')->name('contact.show');

// Sử dụng phương thức POST cho route gửi email từ form contact
Route::post('/contact/send', 'App\Http\Controllers\ContactController@sendEmail')->name('contact.send');

Route::get('/search-result', 'App\Http\Controllers\SearchController@result')->name('search.result');

Route::get('/logout', 'Auth\HomeController@logout')->name('logout');

Route::resource('comments', 'App\Http\Controllers\CommentController');

Route::post('/comments/store', 'CommentController@store')->middleware('auth.comment');

Route::get('/test-mail', 'App\Http\Controllers\TestMailController@SendMail');

Route::get('/home', 'App\Http\Controllers\Homecontroller@home')->name('home');
Route::get('/', function () {
    return view('frontend.index');
});

//Frontend routes
Route::get('contact', 'App\Http\Controllers\Homecontroller@contact')->name('contact');

Route::get('about', 'App\Http\Controllers\Homecontroller@about')->name('about');

Route::get('post-detail/{slug}', 'App\Http\Controllers\Homecontroller@single_post')->name('single-post');

Route::get('single', 'App\Http\Controllers\Homecontroller@single')->name('single');

Route::get('categories/{slug}', 'App\Http\Controllers\Homecontroller@post_categories')->name('post_categories');

Route::group(['middleware'=>'auth'], function () {
});
//Admin routes
Route::group(['middleware'=>['auth','admin']], function () {

    Route::get('/admin/category', 'App\Http\Controllers\Categorycontroller@index')->name('category.index');

    Route::get('/admin/category/create', 'App\Http\Controllers\Categorycontroller@create')->name('category.create');

    Route::post('/admin/category/store', 'App\Http\Controllers\Categorycontroller@store')->name('category.store');

    Route::post('/admin/category/update', 'App\Http\Controllers\Categorycontroller@update')->name('category.update');

    Route::get('/admin/category/edit/{id}', 'App\Http\Controllers\Categorycontroller@edit')->name('category.edit');

    Route::delete('/admin/category/delete' , 'App\Http\Controllers\Categorycontroller@delete')->name('category.delete');

});

//Post routes

Route::get('/admin/posts/delete/{id}', 'App\Http\Controllers\Postcontroller@delete')->name('posts.delete');

Route::resource('posts', 'App\Http\Controllers\Postcontroller');



Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

resources/views/frontend/about.blade.php
@extends('frontend.layouts.master')

@section('content')
<section>
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-12 text-center mb-5">
        <h1 class="page-title">About us</h1>
      </div>
    </div>

    <div class="row mb-5">

      <div class="d-md-flex post-entry-2 half">
        <a href="#" class="me-4 thumbnail">
          <img src="{{asset('frontend/assets/img/post-landscape-2.jpg')}}" alt="" class="img-fluid">
        </a>
        <div class="ps-md-5 mt-4 mt-md-0">
          <div class="post-meta mt-4">About us</div>
          <h2 class="mb-4 display-4">Company History</h2>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores quasi eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente beatae ullam. Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis eligendi.</p>
        </div>
      </div>

      <div class="d-md-flex post-entry-2 half mt-5">
        <a href="#" class="me-4 thumbnail order-2">
          <img src="{{asset('frontend/assets/img/post-landscape-1.jpg')}}" alt="" class="img-fluid">
        </a>
        <div class="pe-md-5 mt-4 mt-md-0">
          <div class="post-meta mt-4">Mission &amp; Vision</div>
          <h2 class="mb-4 display-4">Mission &amp; Vision</h2>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
          <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores quasi eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente beatae ullam. Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis eligendi.</p>
        </div>
      </div>

    </div>

  </div>
</section>

<section class="mb-5 bg-light py-5">
  <div class="container" data-aos="fade-up">
    <div class="row justify-content-between align-items-lg-center">
      <div class="col-lg-5 mb-4 mb-lg-0">
        <h2 class="display-4 mb-4">Latest News</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, rem eaque vel est asperiores iste pariatur placeat molestias, rerum provident ea maiores debitis eum earum esse quas architecto! Minima, voluptatum! Minus tempora distinctio quo sint est blanditiis voluptate eos. Commodi dolore nesciunt culpa adipisci nemo expedita suscipit autem dolorum rerum?</p>
        <p>At magni dolore ullam odio sapiente ipsam, numquam eius minus animi inventore alias quam fugit corrupti error iste laboriosam dolorum culpa doloremque eligendi repellat iusto vel impedit odit cum. Sequi atque molestias nesciunt rem eum pariatur quibusdam deleniti saepe eius maiores porro quam, praesentium ipsa deserunt laboriosam adipisci. Optio, animi!</p>
        <p><a href="#" class="more">View All Blog Posts</a></p>
      </div>
      <div class="col-lg-6">
        <div class="row">
          <div class="col-6">
            <img src="{{asset('frontend/assets/img/post-portrait-3.jpg')}}" alt="" class="img-fluid mb-4">
          </div>
          <div class="col-6 mt-4">
            <img src="{{asset('frontend/assets/img/post-portrait-4.jpg')}}" alt="" class="img-fluid mb-4">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-12 text-center mb-5">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h2 class="display-4">Our Team</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil sint sed, fugit distinctio ad eius itaque deserunt doloribus harum excepturi laudantium sit officiis et eaque blanditiis. Dolore natus excepturi recusandae.</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-1.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Cameron Williamson</h4>
        <span class="d-block mb-3 text-uppercase">Founder &amp; CEO</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-2.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Wade Warren</h4>
        <span class="d-block mb-3 text-uppercase">Founder, VP</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-3.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Jane Cooper</h4>
        <span class="d-block mb-3 text-uppercase">Editor Staff</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-4.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Cameron Williamson</h4>
        <span class="d-block mb-3 text-uppercase">Editor Staff</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-5.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Cameron Williamson</h4>
        <span class="d-block mb-3 text-uppercase">Editor Staff</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
      <div class="col-lg-4 text-center mb-5">
        <img src="{{asset('frontend/assets/img/person-6.jpg')}}" alt="" class="img-fluid rounded-circle w-50 mb-4">
        <h4>Cameron Williamson</h4>
        <span class="d-block mb-3 text-uppercase">Editor Staff</span>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/frontend/category-posts.blade.php
@extends('frontend.layouts.master')

@section('content')
<section id="search-result" class="search-result">
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <h3 class="category-title">Tin </h3>

          @foreach ($posts as $item)
          <div class="d-md-flex post-entry-2 small-img">
            <a href="{{ route('single-post',$item->slug) }}" class="me-4 thumbnail">
              <img src="{{ asset('uploads/post/' .$item->photo) }}" alt="" class="img-fluid">
            </a>
            <div>
              <div class="post-meta"><span class="date">{{ $item->category->name }}</span> <span class="mx-1">&bullet;</span> <span>{{ format_date($item->created_at) }}</span></div> 
              <h3><a href="{{ route('single-post',$item->slug) }}">{{ $item->title }}</a></h3>
              <p>{{text_short($item->short_description, 500) }}</p>
              <div class="d-flex align-items-center author">
                <div class="photo"><img src="assets/img/person-2.jpg" alt="" class="img-fluid"></div>
                <div class="name">
                  <h3 class="m-0 p-0">Người đăng: {{ $item->user->name }}</h3>
                </div>
              </div>
            </div>
          </div>
          @endforeach         
          <!-- Paging -->
          <div class="text-start py-4">
            <div class="custom-pagination">
              <a href="#" class="prev">Prevous</a>
              <a href="#" class="active">1</a>
              <a href="#">2</a>
              <a href="#">3</a>
              <a href="#">4</a>
              <a href="#">5</a>
              <a href="#" class="next">Next</a>
            </div>
          </div><!-- End Paging -->

        </div>
        <div class="col-md-3">
            @include('frontend.inc.sidebar')
        </div>
      </div>
    </div>
  </section> 
@endsection

resources/views/frontend/contact.blade.php
@extends('frontend.layouts.master')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Trang Contact</div>

                    <div class="card-body">
                        @if(session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif

                        <form action="{{ route('contact.send') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="name">Tên của bạn</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="message">Lời góp ý/phản ánh</label>
                                <textarea name="message" class="form-control" rows="5" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Gửi</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/index.blade.php
@extends('frontend.layouts.master')
@push('meta')
    <meta content="" name="description">
    <meta content="" name="keywords">
@endpush
@section('content')

    <section id="hero-slider" class="hero-slider">
        <div class="container-md" data-aos="fade-in">
            <div class="row">
                <div class="col-12">
                    <div class="swiper sliderFeaturedPosts">
                        <div class="swiper-wrapper">
                            @php
                                $posts = App\Models\Post::orderBy('views', 'DESC')->take(5)->get();
                                $count = 1;
                            @endphp
                            @foreach ($posts as $item)
                                <div class="swiper-slide">
                                    <a href="{{ route('single-post', $item->slug) }}" class="img-bg d-flex align-items-end"
                                        style="background-image: url('{{ asset('uploads/post/' . $item->photo) }}');">
                                        <div class="img-bg-inner">
                                            <h2>{{ $item->title }}</h2>
                                            <p>{{ $item->excerpt }}</p>
                                        </div>
                                    </a>
                                </div>
                                @php
                                    $count++;
                                @endphp
                            @endforeach
                        </div>
                        <div class="custom-swiper-button-next">
                            <span class="bi-chevron-right"></span>
                        </div>
                        <div class="custom-swiper-button-prev">
                            <span class="bi-chevron-left"></span>
                        </div>

                        <div class="swiper-pagination"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {{-- Phần tin mới và tin nóng --}}

    <section id="posts" class="posts">
        <div class="container" data-aos="fade-up">
            <div class="section-header d-flex justify-content-between align-items-center mb-5">
                <h2>Tin mới</h2>
            </div>
            <div class="row g-5">
                <div class="col-lg-4">

                    @php
                        $posts = App\Models\Post::latest()->take(6)->get();
                    @endphp
                    @foreach ($posts as $index => $post)
                        @if ($index < 3)
                            <div class="post-entry-1 lg">
                                <a href="{{ route('single-post', $post->slug) }}"><img
                                        src="{{ asset('uploads/post/' . $post->photo) }}" alt=""
                                        class="img-fluid"></a>
                                <div class="post-meta"><span class="date">{{ $post->category->name }}</span> <span
                                        class="mx-1">&bullet;</span> <span>{{ format_date($post->created_at) }}</span>
                                </div>
                                <h2 style="font-size: 18px;"><a
                                        href="{{ route('single-post', $post->slug) }}">{{ $post->title }}</a></h2>
                                <p class="mb-4 d-block" style="font-size: 16px;">{{ $post->excerpt }}</p>
                                <div class="d-flex align-items-center author">
                                    <div class="photo"><img src="{{ asset('assets/img/person-1.jpg') }}" alt=""
                                            class="img-fluid"></div>
                                    <div class="name">
                                        <h3 class="m-0 p-0" style="font-size: 16px;">{{ $post->author }}</h3>
                                    </div>
                                </div>
                            </div>
                        @endif
                    @endforeach
                </div>

                <div class="col-lg-8">
                    <div class="row g-5">
                        <div class="col-lg-6 border-start custom-border">
                            @foreach ($posts as $index => $post)
                                @if ($index >= 3)
                                    <div class="post-entry-1">
                                        <a href="{{ route('single-post', $post->slug) }}"><img
                                                src="{{ asset('uploads/post/' . $post->photo) }}" alt=""
                                                class="img-fluid"></a>
                                        <div class="post-meta"><span class="date">{{ $post->category->name }}</span>
                                            <span class="mx-1">&bullet;</span>
                                            <span>{{ format_date($post->created_at) }}</span></div>
                                        <h2><a href="{{ route('single-post', $post->slug) }}">{{ $post->title }}</a></h2>
                                    </div>
                                @endif
                            @endforeach
                        </div>

                        <div class="col-lg-6">
                            <div class="trending text-end">
                                <h3>Tin nóng</h3>
                                <ul class="trending-post">
                                    @php
                                        // Dùng orderBy() để sắp xếp, DESC tham số giảm dần
                                        $posts = App\Models\Post::orderBy('views', 'DESC')->take(10)->get();
                                        $count = 1;
                                    @endphp

                                    @foreach ($posts as $post)
                                        <li>
                                            <a href="{{ route('single-post', $post->slug) }}">
                                                <span class="number">{{ $count }}</span>
                                                <h3>{{ $post->title }}</h3>
                                                <span class="author">{{ $post->author }}</span>
                                            </a>
                                        </li>
                                        @php
                                            $count++;
                                        @endphp
                                    @endforeach
                                </ul>
                            </div>
                            <br><br>
                            @php
                            $categories = \App\Models\Category::where('status','Active')->latest()->take(8)->get();
                        @endphp
                          <div class="aside-block">
                            <h3 class="aside-title">Thể loại tin</h3>
                            <ul class="aside-links list-unstyled">
                                @foreach ($categories as $category)
                                    <li><a href="{{ route('post_categories',$category->slug) }}"><i class="bi bi-chevron-right"></i> {{ $category->name }}</a></li>
                                @endforeach
                            </ul>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    @php
        $categories = App\Models\Category::where('status', 'Active')->latest()->get();
        // dd($categories);
    @endphp
    @foreach ($categories as $category)
        {{-- {{ dd($category->id)}}  --}}

        <section class="category-section">
            <div class="container" data-aos="fade-up">

                <div class="section-header d-flex justify-content-between align-items-center mb-5">
                    <h2>{{ $category->name }}</h2>
                    <div><a href="{{ route('post_categories', $category->slug) }}" class="more"> Xem thêm
                            {{ $category->name }}</a></div>
                </div>

                <div class="row">
                    <div class="col-md-9">
                        <div class="row">
                            @php
                                $posts = App\Models\Post::where('status', 'Active')
                                    ->where('category_id', $category->id)
                                    ->latest()
                                    ->take(3)
                                    ->get();
                            @endphp
                            @foreach ($posts as $item)
                                <div class="col-lg-4">
                                    <div class="post-entry-1 border-bottom">
                                        <a href="{{ route('single-post', $item->slug) }}"><img
                                                src="{{ asset('uploads/post/' . $item->photo) }}" alt=""
                                                class="img-fluid"></a>
                                        <div class="post-meta"><span class="date">{{ $item->category->name }}</span>
                                            <span class="mx-1">&bullet;</span>
                                            <span>{{ format_date($item->created_at) }}</span>
                                        </div>
                                        <h2 class="mb-2"><a
                                                href="{{ route('single-post', $item->slug) }}">{{ $item->title }}</a>
                                        </h2>
                                        <span class="author mb-3 d-block">{{ $item->user->name }}</span>
                                        <p class="mb-4 d-block">{{ text_short($item->short_description, 500) }}</p>
                                    </div>
                                </div>
                            @endforeach

                        </div>
                    </div>

                    <div class="col-md-3">

                        @foreach ($posts as $item)
                            <div class="post-entry-1 border-bottom">
                                <div class="post-meta"><span class="date">{{ $item->category->name }}</span> <span
                                        class="mx-1">&bullet;</span> <span>{{ format_date($item->created_at) }}</span>
                                </div>
                                <h2 class="mb-2"><a
                                        href="{{ route('single-post', $item->slug) }}">{{ $item->title }}</a></h2>
                                <span class="author mb-3 d-block">{{ $item->user->name }}</span>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </section>
    @endforeach
@endsection

resources/views/frontend/single-post.blade.php
@extends('frontend.layouts.master')
@push('meta')
    <title>
        {{ $post->title }}</title>

    <meta content="{{ text_short($post->description, 500) }}" name="description">
    <meta content="{{ make_keyword($post->title) }}" name="keywords">
    <meta content="{{ $post->title }}" name="title">
@endpush

@section('content')

    <section class="single-post-content">
        <div class="container">
            <div class="row">
                <div class="col-md-9 post-content" data-aos="fade-up">

                    <!-- ======= Single Post Content ======= -->
                    <div class="single-post">
                        <div class="post-meta"><span class="date">{{ $post->category->name }}</span> <span
                                class="mx-1">&bullet;</span> <span>{{ format_date($post->created_at) }}</span></div>
                        <h1 class="mb-5">{{ $post->title }}</h1>
                        <div class="post-views"
                            style="background-color: #f0f0f0; border-radius: 10px; padding: 10px; display: flex; align-items: center;">
                            <div>
                                <h5>Người đăng: {{ $post->user->name }}</h5>
                            </div>
                        </div>
                        <br>
                        <h4 class="bold-text">{{ $post->short_description }}</h4>

                        <figure class="my-4">
                            <img src="{{ asset('uploads/post/' . $post->photo) }}" alt="" class="img-fluid">

                        </figure>

                        <div>
                            {!! $post->description !!}
                        </div>
                    </div>
                    <div>
                        <div class="post-views"
                            style="background-color: #f0f0f0; border-radius: 10px; padding: 10px; display: flex; align-items: center;">
                            <div class="view-count">
                                <h5 class="your-class-name"><i class="far fa-eye"></i> Lượt xem: {{ $post->views }}</h5>
                            </div>
                            <div style="margin-left: auto;">
                                <p>Bài đăng lúc: {{ format_date($post->created_at) }}</p>
                            </div>
                        </div>
                    </div>
                    <br><br>
                    <h3>Các Bình luận</h3>
                    @foreach ($post->comments as $comment)
                    <div class="comment">
                        {{-- Kiểm tra nếu có người dùng được liên kết với bình luận --}}
                        @if ($comment->user)
                            {{-- Hiển thị tên người dùng và nội dung bình luận --}}
                            
                            <div class="comment-user">
                               
                                <strong>{{ $comment->user->name }}</strong> đã bình luận: {{ $comment->content }}
                            </div>
                        @else
                            {{-- Hiển thị thông báo nếu không có người dùng --}}
                            <div class="comment-user">
                                Người dùng không xác định đã bình luận: {{ $comment->content }}
                            </div>
                        @endif
                    </div>              
                    
                    @endforeach
                    <br><br>
                    <!-- ======= Comments Form ======= -->
                    @if (Auth::check())
                        <!-- Form bình luận -->
                        <form action="{{ route('comments.store') }}" method="post">
                            @csrf
                            <input type="hidden" name="post_id" value="{{ $post->id }}">
                            <div class="col-12 mb-3">
                                <h3 for="comment-message">Viết Bình luận</h3>
                                <textarea name="content" class="form-control" id="comment-message" placeholder="Bình luận của bạn" cols="30"
                                    rows="10"></textarea>
                            </div>
                            <div class="col-12">
                                <input type="submit" class="btn btn-primary" value="Bình Luận">
                            </div>
                        </form>
                    @else
                        <p>Bạn cần đăng nhập để bình luận.</p>
                    @endif
                </div>

                <div class="col-md-3">
                    @include('frontend.inc.sidebar')
                </div>
            </div>
        </div>
    </section>