routes/web.php
<?php

use App\Mail\WelcomeMail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Sử dụng phương thức GET cho route hiển thị form contact
Route::get('/contact', 'App\Http\Controllers\ContactController@showForm')->name('contact.show');

// Sử dụng phương thức POST cho route gửi email từ form contact
Route::post('/contact/send', 'App\Http\Controllers\ContactController@sendEmail')->name('contact.send');

Route::get('/search-result', 'App\Http\Controllers\SearchController@result')->name('search.result');

Route::get('/logout', 'Auth\HomeController@logout')->name('logout');

Route::resource('comments', 'App\Http\Controllers\CommentController');

Route::post('/comments/store', 'CommentController@store')->middleware('auth.comment');

Route::get('/test-mail', 'App\Http\Controllers\TestMailController@SendMail');

Route::get('/home', 'App\Http\Controllers\Homecontroller@home')->name('home');
Route::get('/', function () {
    return view('frontend.index');
});

//Frontend routes
Route::get('contact', 'App\Http\Controllers\Homecontroller@contact')->name('contact');

Route::get('about', 'App\Http\Controllers\Homecontroller@about')->name('about');

Route::get('post-detail/{slug}', 'App\Http\Controllers\Homecontroller@single_post')->name('single-post');

Route::get('single', 'App\Http\Controllers\Homecontroller@single')->name('single');

Route::get('categories/{slug}', 'App\Http\Controllers\Homecontroller@post_categories')->name('post_categories');

Route::group(['middleware'=>'auth'], function () {
});
//Admin routes
Route::group(['middleware'=>['auth','admin']], function () {

    Route::get('/admin/category', 'App\Http\Controllers\Categorycontroller@index')->name('category.index');

    Route::get('/admin/category/create', 'App\Http\Controllers\Categorycontroller@create')->name('category.create');

    Route::post('/admin/category/store', 'App\Http\Controllers\Categorycontroller@store')->name('category.store');

    Route::post('/admin/category/update', 'App\Http\Controllers\Categorycontroller@update')->name('category.update');

    Route::get('/admin/category/edit/{id}', 'App\Http\Controllers\Categorycontroller@edit')->name('category.edit');

    Route::delete('/admin/category/delete' , 'App\Http\Controllers\Categorycontroller@delete')->name('category.delete');

});

//Post routes

Route::get('/admin/posts/delete/{id}', 'App\Http\Controllers\Postcontroller@delete')->name('posts.delete');

Route::resource('posts', 'App\Http\Controllers\Postcontroller');



Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class, 'added_by');
    }
    public function comments()
{
    return $this->hasMany(Comment::class);
}
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
    class PostController extends Controller
    {
        
        public function index()
        {
            $models = Post::with('category')->paginate(5);
            return view('admin.post.index',compact('models'));
        }

    
        public function create()
        {
            $models = Category::where('status', 'Active')->get();
            return view('admin.post.create',compact('models'));
        }

        public function store(Request $request)
        {
        $request->validate([
                'title' => ['required','unique:posts'],
                'category_id' => ['required'],
                'status' => ['required'],
                'short_description' => ['required'],
                'description' => ['required'],
                'photo' => ['required']
        ]);
        
        
    // composer require intervention/image
    // thư viện hình ảnh Intervention Image
        $model = new Post;
        $model->title = $request->title;
        $model->category_id = $request->category_id;
        $model->added_by = Auth::user()->id;
        $model->status = $request->status;
        $model->short_description = $request->short_description;
        $model->description = $request->description;
        $model->slug = Str::slug($request->title);

        if($request->hasFile('photo')){
                $file = $request->file('photo');
                $ext = $file->extension() ? : 'png';
                $photo = Str::random(10) . '.' . $ext;

                // resize image

                $path = public_path(). '/uploads/post/';
                $resize = Image::make($file->getRealPath());
                $resize->resize(900,570);
                $resize->save($path.'/'.$photo);

                $model->photo = $photo;
        }
        $model->save();
            return redirect()->route('posts.index')->with('message','Post Insert Successfully');      
        }

    
        public function show(Post $post)
        {
            dd($post);
        }
        public function edit($id)
        {
            $model = Post::findOrFail($id);
            $models = Category::where('status','Active')->get();
            return view('admin.post.edit',compact('models','model'));
        }

    
        public function update(Request $request, Post $post)
        {
            //dd($request->all());
        $model = $post;
        $model->title = $request->title;
        $model->category_id = $request->category_id;
        $model->status = $request->status;
        $model->short_description = $request->short_description;
        $model->description = $request->description;
        $model->slug = Str::slug($request->title);

        if($request->hasFile('photo')){
                $file = $request->file('photo');
                $ext = $file->extension() ? : 'png';
                $photo = Str::random(10) . '.' . $ext;

                // resize image

                $path = public_path(). '/uploads/post/';
                $resize = Image::make($file->getRealPath());
                $resize->resize(900,570);

                // Old Photo Delete 
                if($request->old_photo){
                    $oldphoto = public_path(). '/uploads/post/'.$request->old_photo;
                    unlink($oldphoto);
                }
                $resize->save($path.'/'.$photo);

                $model->photo = $photo;
        }

        $model->save();

            return redirect()->route('posts.index')->with('message','Post Update Successfully');
        }
        
        public function destroy(Post $post)
        {
            dd($post);
        }
        public function delete($id)
        {
            $model = Post::findOrFail($id);
            if($model->photo){
                $oldphoto = public_path(). '/uploads/post/'.$model->photo;
                unlink($oldphoto);
            }
            $model->delete();
        }

    
        
    }

resources/views/admin/post/create.blade.php
@extends('admin.layouts.master')
@push('style')
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
@endpush
@section('content')
    
<div class="pagetitle">
    <h1>Bài Đăng</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{route('home')}}">Trang chủ</a></li>
        <li class="breadcrumb-item active">Bài Đăng</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Thêm bài đăng</h5>
          
            <!-- Custom Styled Validation -->
            <form class="row g-3 needs-validation" enctype="multipart/form-data" method="post" action="{{route('posts.store')}}" novalidate >
              @csrf

              <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Post Titles</label>
                <input type="text" placeholder="Type posts titles" class="form-control" id="validationCustom01" name="title" required>  
                @if ($errors->has('title'))
                <span class="text-danger">{{ $errors->first('title') }}</span>
              @endif
                        
              </div>

              <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Post Category</label>
                <select name="category_id" id="" class="form-control">
                  <option value="">Select Category</option>
                  @foreach ($models as $item)
                  <option value="{{$item->id}}">{{$item->name}}</option>
                  @endforeach
                </select>      
              </div>

              <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Post Photo</label>
              <input type="file" class="form-control" id="validationCustom01" name="photo" required>
              </div>

              <div class="col-md-6">
                <label for="validationCustom04" class="form-label">Status</label>
                <select name="status" class="form-select" id="validationCustom04" required>
                  <option selected disabled value="">Choose status</option>
                  <option value="Active">Active</option>
                  <option value="Inactive">Inactive</option>
                </select>               
              </div>

              <div class="col-md-12">
                <label for="validationCustom04" class="form-label">Short Description </label>
                <textarea name="short_description" id="" class="form-control" cols="10" rows="1"></textarea>      
              </div>

              <div class="col-md-12">
                <label for="validationCustom04" class="form-label">Description </label>
                <textarea name="description" id="" class="form-control summernote" cols="30" rows="10"></textarea>      
              </div>

              <div class="col-12">
                <button class="btn btn-primary" type="submit">Submit</button>
              </div>
            </form><!-- End Custom Styled Validation -->

          </div>
        </div>
      </div>
    </div>
  </section>

@endsection

@push('script')
<script type="text/javascript">
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script> 
@endpush

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.master')
@push('style')
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
@endpush
@section('content')



<div class="pagetitle">
    <h1>Post</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
        <li class="breadcrumb-item active">Post</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      

      <div class="col-lg-12">

        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Add Post</h5>

            <!-- Custom Styled Validation -->
            <form class="row g-3 needs-validation" enctype="multipart/form-data" method="post" action="{{ route('posts.update', $model->id) }}" novalidate >
              @csrf
              @method('PATCH')
              <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Post Title</label>
                <input value="{{ $model->title }}" type="text" placeholder="type post title" class="form-control" id="validationCustom01" name="title" required>
                @if ($errors->has('title'))
                  <span class="text-danger">{{ $errors->first('title') }}</span>
                @endif
              </div>

              <div class="col-md-6">
                <label for="validationCustom01" class="form-label">Post Category</label>
                <select name="category_id" id="" class="form-control">
                  <option value="">Select Category</option>
                  @foreach ($models as $item)
                  <option {{ $model->category_id == $item->id ? 'selected':'' }} value="{{ $item->id }}">{{ $item->name }}</option>
                  @endforeach
                </select>
              </div>


              <div class="col-md-2">
                <label for="validationCustom01" class="form-label">Post Photo</label>
                <input type="hidden" value="{{ $model->photo }}"  class="form-control"  name="old_photo" >
                <img src="{{ asset('uploads/post/'.$model->photo) }}" width="120" height="80" alt="">
              </div>
              

              <div class="col-md-4">
                <label for="validationCustom01" class="form-label">Post Photo</label>
                <input type="file"  class="form-control" id="validationCustom01" name="photo" >
              </div>

              <div class="col-md-6">
                <label for="validationCustom04" class="form-label">Status</label>
                <select name="status" class="form-select" id="validationCustom04" required>
                  <option selected disabled value="">Choose Status...</option>
                  <option {{ $model->status == "Active" ? 'selected':'' }} value="Active">Active</option>
                  <option {{ $model->status == "Inactive" ? 'selected':'' }}  value="Inactive">Inactive</option>
                </select>
              </div>

              <div class="col-md-12">
                <label for="validationCustom04" class="form-label">Short Description</label>
                <textarea  name="short_description" id="" cols="30" rows="10" class="form-control">{{ $model->short_description }}</textarea>
              </div>

              
              <div class="col-md-12">
                <label for="validationCustom04" class="form-label"> Description</label>
                <textarea name="description" id="" cols="30" rows="10" class="form-control summernote">{{ $model->description }}</textarea>
              </div>

              <div class="col-12">
                      <button class="btn btn-primary" type="submit">Update</button>
                    </div>
                  </form>

                </div>
              </div>

      </div>
    </div>
  </section>



@endsection

@push('script')
<script type="text/javascript">
  $(document).ready(function() {
    $('.summernote').summernote();
  });
</script>
@endpush

resources/views/admin/post/index.blade.php
@extends('admin.layouts.master')

@section('content')

<div class="pagetitle">
    <h1>Post</h1>
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
        <li class="breadcrumb-item active">Post</li>
      </ol>
    </nav>
  </div><!-- End Page Title -->

  <section class="section">
    <div class="row">
      

      <div class="col-lg-12">

        <div class="card">
            <div class="card-body">
              <h5 class="card-title">All Posts</h5>

              <!-- Default Table -->
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Category</th>
                    <th scope="col">Photo</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($models as $model)
                        
                  <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $model->title }}</td>
                    <td>{{ optional($model->category)->name }}</td>
                    <td>
                      <img src="{{ asset('uploads/post/' . $model->photo) }}" width="120" height="80" alt="">
                      
                    </td>
                    <td>{{ $model->status }}</td>
                    <td>
                        <a class="btn btn-warning" href="{{ route('posts.edit',$model->id) }}">Edit</a>
                        <a onclick=" return confirm('Are you sure you want to delete this item?');" class="btn btn-danger" href="{{ route('posts.delete',$model->id) }}">Delete</a>
                    </td>

                  </tr>
                  
                  @endforeach
                  
                </tbody>
              </table>
              <!-- End Default Table Example -->
            </div>
          </div>

      </div>
    </div>
  </section>



@endsection